apiVersion: apps/v1
kind: Deployment
metadata:
  name: project01-backend
  namespace: staging
  labels:
    app: project01
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project01
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: project01
        component: backend
    spec:
      containers:
      - name: backend
        image: project01:latest-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "staging"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: API_PREFIX
          value: "/api"
        - name: CORS_ORIGINS
          value: "https://staging.project01.example.com"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: project01-secrets
              key: jwt-secret
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"
        - name: CACHE_TTL
          value: "3600"
        - name: RATE_LIMIT_REQUESTS
          value: "100"
        - name: RATE_LIMIT_WINDOW
          value: "60"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: project01-models-pvc
      - name: cache-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: project01-backend
  namespace: staging
  labels:
    app: project01
    component: backend
spec:
  selector:
    app: project01
    component: backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project01-models-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
