global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'baseline-service'
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: baseline
        action: keep
      - source_labels: [__meta_kubernetes_service_port_name]
        regex: metrics
        action: keep
      - source_labels: [__address__]
        target_label: __address__
        regex: (.+)(?::\d+)
        replacement: $1:8000

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
