name: Lint and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install only essential dependencies for testing
          pip install pytest flake8 numpy pandas gymnasium==0.29.1

      - name: Lint code
        run: |
          # Run flake8 with relaxed settings
          echo "Running flake8 with relaxed settings..."
          flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "Flake8 completed successfully."

      - name: Run tests
        run: |
          echo "Running tests..."
          # Run tests with more detailed output and continue on error
          python -m pytest tests/test_rl_env.py -v --tb=native || {
            echo "Some tests failed. Check the output above for details."
            exit 1
          }
          echo "All tests passed successfully."
